### ISSUE TITLE
example from youtube doesn't work:ENGyn : Set property value to object

### ISSUE THREAD

**Issue by AlexSyxorykov** [ENGworks-DEV/ENGyn#59]
Try to repeat the example from youtube "ENGyn : Set property value to object" but it seems doesn't work properly, in the end don't have desire resalt
Attach file.
Use Navisworks Manage 2018
Can it be the problem with localization? Use Russian language
![555555](https://user-images.githubusercontent.com/34717441/49386153-02aa3480-f730-11e8-9059-50035416b552.png)

**Comment by pabloderen** [comment]
Download the installers from here:
https://github.com/ENGworks-DEV/ENGyn/releases/tag/0.1.4.5alpha4.5
