### ISSUE TITLE
Looks like Node "GroupByCluster" doesn't work properly 

### ISSUE THREAD

**Issue by AlexSyxorykov** [ENGworks-DEV/ENGyn#62]
Looks like Node "GroupByCluster" doesn't work properly 
Works only with the first ClushTest (see the picture )
After using this test navisworks just freeze
![groupbycluster](https://user-images.githubusercontent.com/34717441/49746859-267ef480-fcb3-11e8-9fab-483642b8c5b3.png)

**Comment by ENGworks-DEV** [comment]
Fixed in a27a15bf
