### ISSUE TITLE
ENGYN/ Add properties by SelectionSet

### ISSUE THREAD

**Issue by MatteoCapoferri** [ENGworks-DEV/ENGyn#67]
Hi Engyn team!!! @ENGworks-DEV 
It's possible somehow in a fast way to add custom properties for a Selection of objects. In someway do exactly what DataTools do but in a faster and smarter way.
The path could be:
Input(selection sets)>>
Input(property to add)>>      @# Output(where to add property)(set an old/new category properties) 

Thanks

Matteo

**Comment by ENGworks-DEV** [comment]
Hi Matteo, what you are looking is something like this:
![image](https://user-images.githubusercontent.com/42068789/50156275-27181c00-02ad-11e9-9835-257b1258403c.png)

Note that now (latest version of code soon to be publish) you can use GetSelectionByGuid to select an element by its GUID. If you use it with Excel nodes you can assign properties from a spreadsheet to specific objects in the model.

![image](https://user-images.githubusercontent.com/42068789/50158004-a871ad80-02b1-11e9-8d83-3874f5d892ce.png)
